### ISSUE TITLE
Index fields as text for full-text search and keyword for sorting and aggregations

### ISSUE THREAD

**Issue by gurbirkalsi** [atheurer/CommonDataModel#2]
In order to support functionality such as building visualizations and filtering within the benchpress dashboard, specific fields that are indexed as `text` values need to be indexed as `keyword` values in order to support aggregation queries and sorting. 

In the `run.json` definition, we'll need to update field types for the following field names:
```
run.tool_names
run.user.desc
run.bench.clients
run.bench.params
run.bench.servers
run.start
run.end
```

Elasticsearch provides an example showing the addition of multiple field types for a document field
[https://www.elastic.co/guide/en/elasticsearch/reference/master/multi-fields.html](https://www.elastic.co/guide/en/elasticsearch/reference/master/multi-fields.html)
```JSON
{
  "mappings": {
    "properties": {
      "city": {
        "type": "text",
        "fields": {
          "raw": { 
            "type":  "keyword"
          }
        }
      }
    }
  }
}
```

**Comment by atheurer** [comment]
Thanks for pointing this out. I’ll update the templates and try to update the mapping in our current test instance

**Comment by atheurer** [comment]
@gurbirkalsi I am wondering if this multi-field feature is going to work, as the reference page states:

You are looking at preliminary documentation for a future release.

Also some comments on each of these fields:

run.tool_names, run.bench.clients, run.bench.params, run.bench.servers
- These are all lists.  Don't we want these to get tokenized, and if so, is that possible with type keyword?

run.start (do you mean run.begin?) and run.end
- I thought it was important to keep these as date data type

@portante what are your thoughts on this?

**Comment by portante** [comment]
@atheurer, the multi-field feature appears fully supported in 6.6 and early, even as far back as 2.x I believe.

For the lists, we could use a tokenizer so that the separator for the list elements is what defines the token instead of using `keyword`.

+1 on keeping `run.begin`/`run.end` as dates.

**Comment by atheurer** [comment]
@gurbirkalsi @portante OK, I have updated the mapping for run in our staging instance, but I have not updated this repo yet because I need to decide how these mappings get stored in git.  The issue is that currently these are stored within templates.  However, you cannot update (add this multi-field) and reapply a template to an existing index.  You must update only the mapping, which looks different, for example:

<pre>
{
  "dynamic": false,
  "properties": {
    "cdm": {
      "properties": {
        "ver": { "type": "integer" },
        "doctype": { "type": "keyword" }
      }
    },
    "run": {
      "properties": {
        "id": { "type": "keyword" },
        "begin": { "type": "date" },
        "end": { "type": "date" },
        "harness_name": { "type": "keyword" },
        "host": { "type": "keyword" },
        "ignore": { "type": "boolean" },
        "tool_names": { "type": "text", "fields": { "raw": { "type":  "keyword" } } },
        "data_source": { "type": "keyword" },
        "label": { "type": "keyword" },
        "user": {
          "properties": {
            "desc": { "type": "text" },
            "email": { "type": "keyword" },
            "name": { "type": "keyword" },
            "tags": { "type": "text", "fields": { "raw": { "type":  "keyword" } } }
          }
        },
        "bench": {
          "properties": {
            "clients": { "type": "text", "fields": { "raw": { "type":  "keyword" } } },
            "name": { "type": "keyword" },
            "params": { "type": "text", "fields": { "raw": { "type":  "keyword" } } },
            "servers": { "type": "text", "fields": { "raw": { "type":  "keyword" } } }
          }
        }
      }
    }
  }
}
</pre>

And then update via:

curl -X PUT $es_url/cdmv3dev-run/_mapping/run  -H 'Content-Type: application/json' -d@./run-mapping.json.

So, that makes me wonder, should we maintain two files for each index, a template (without mappings, what else would it really have?) and a mapping?

**Comment by portante** [comment]
@atheurer, we sort of do it that way in pbench today.  Take a look at the `server/pbench/lib/mappings` and the `es_template()` routine in `index-pbench`.

**Comment by atheurer** [comment]
I forgot to mention:  I am creating the new field under user, user.tags, and I am leaving user.desc as text, and user.tags will be "tags": { "type": "text", "fields": { "raw": { "type":  "keyword" } } }.

I don't think having desc as being tokenized or as a keyword makes much sense, and this is a free-form description of what the test was about, typically something like a paragraph.  I don't think this is suitable for searching, but only used for reading once you have found the result you want.

Tags, on the other hand, should be a simple list of words that are relevant to the run, like, "beta, upstream, NFV, k8s, super-scale".  This is the type of data we can tokenize easily and search/filter on.  We will just add a option for our test harnesses (pbench, browbeat, etc) to have --user-tags= when a user runs their benchmark.

User.desc, ideally, would be used to give more detailed information in paragraph form, perhaps providing post-run analysis and/or notes once the user had the opportunity to see the outcome of the test.  At some point, it would be very useful for the user to add this information *through* the UI.
